[project]
name = "keyword-selection"
version = "0.1.0"
description = "Extraction of keywords regarding Russia-Ukraine war from German parliamentary debates"
readme = "README.md"
authors = [
    { name = "Fabian Simonjetz", email = "fsimonjetz@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "bertopic>=0.17.4",
    "ipykernel>=7.3.0",
    "ipywidgets>=8.1.9",
    "jupyter>=1.1.1",
    "pandas[parquet]>=3.0.5",
    "requests>=2.34.2",
    "spacy>=3.8.16",
    "stop-words>=2025.11.4",
]

[project.scripts]
keyword-selection = "keyword_selection:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
